declare namespace _default {
	export { isArray as array };
	export { isBoolean as boolean };
	export { isDate as date };
	export { isFloat as float };
	export { isFunction as function };
	export { isInstanceOf as instanceOf };
	export { isInteger as integer };
	export { isJson as json };
	export { isMap as map };
	export { isNumber as number };
	export { isObject as object };
	export { isPromise as promise };
	export { isRegExp as regExp };
	export { isSet as set };
	export { isString as string };
	export { isSymbol as symbol };
	export { isWeakMap as weakMap };
	export { isWeakSet as weakSet };
}
export default _default;
import isArray from './isArray.js';
import isBoolean from './isBoolean.js';
import isDate from './isDate.js';
import isFloat from './isFloat.js';
import isFunction from './isFunction.js';
import isInstanceOf from './isInstanceOf.js';
import isInteger from './isInteger.js';
import isJson from './isJson.js';
import isMap from './isMap.js';
import isNumber from './isNumber.js';
import isObject from './isObject.js';
import isPromise from './isPromise.js';
import isRegExp from './isRegExp.js';
import isSet from './isSet.js';
import isString from './isString.js';
import isSymbol from './isSymbol.js';
import isWeakMap from './isWeakMap.js';
import isWeakSet from './isWeakSet.js';
