declare namespace _default {
	export { methodAny as any };
	export { methodArray as array };
	export { methodBoolean as boolean };
	export { methodQueue as queue };
	export { methodDate as date };
	export { methodEnum as enum };
	export { methodFloat as float };
	export { methodFunction as function };
	export { methodInteger as integer };
	export { methodInstanceOf as instanceOf };
	export { methodKeyValue as keyValue };
	export { methodMap as map };
	export { methodNumber as number };
	export { methodObject as object };
	export { methodPromise as promise };
	export { methodRegExp as regExp };
	export { methodSet as set };
	export { methodString as string };
	export { methodSymbol as symbol };
	export { methodWeakMap as weakMap };
	export { methodWeakSet as weakSet };
}
export default _default;
import methodAny from './methodAny.js';
import methodArray from './methodArray.js';
import methodBoolean from './methodBoolean.js';
import methodQueue from './methodQueue.js';
import methodDate from './methodDate.js';
import methodEnum from './methodEnum.js';
import methodFloat from './methodFloat.js';
import methodFunction from './methodFunction.js';
import methodInteger from './methodInteger.js';
import methodInstanceOf from './methodInstanceOf.js';
import methodKeyValue from './methodKeyValue.js';
import methodMap from './methodMap.js';
import methodNumber from './methodNumber.js';
import methodObject from './methodObject.js';
import methodPromise from './methodPromise.js';
import methodRegExp from './methodRegExp.js';
import methodSet from './methodSet.js';
import methodString from './methodString.js';
import methodSymbol from './methodSymbol.js';
import methodWeakMap from './methodWeakMap.js';
import methodWeakSet from './methodWeakSet.js';
