declare namespace _default {
	export { enforceArray as array };
	export { enforceBoolean as boolean };
	export { enforceDate as date };
	export { enforceEnum as enum };
	export { enforceFloat as float };
	export { enforceFunction as function };
	export { enforceInstanceOf as instanceOf };
	export { enforceInteger as integer };
	export { enforceMap as map };
	export { enforceNumber as number };
	export { enforceObject as object };
	export { enforcePromise as promise };
	export { enforceRegExp as regExp };
	export { enforceSet as set };
	export { enforceString as string };
	export { enforceSymbol as symbol };
	export { enforceWeakMap as weakMap };
	export { enforceWeakSet as weakSet };
}
export default _default;
import enforceArray from './enforceArray.js';
import enforceBoolean from './enforceBoolean.js';
import enforceDate from './enforceDate.js';
import enforceEnum from './enforceEnum.js';
import enforceFloat from './enforceFloat.js';
import enforceFunction from './enforceFunction.js';
import enforceInstanceOf from './enforceInstanceOf.js';
import enforceInteger from './enforceInteger.js';
import enforceMap from './enforceMap.js';
import enforceNumber from './enforceNumber.js';
import enforceObject from './enforceObject.js';
import enforcePromise from './enforcePromise.js';
import enforceRegExp from './enforceRegExp.js';
import enforceSet from './enforceSet.js';
import enforceString from './enforceString.js';
import enforceSymbol from './enforceSymbol.js';
import enforceWeakMap from './enforceWeakMap.js';
import enforceWeakSet from './enforceWeakSet.js';
